import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "KC Lash",
  description: "Generated by create next app",
  googleSiteVerification: "umb7i7RrvWJyo4Zdb9BtXM7gC4rHnGYHsy9sPKYarRI",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
