import { Inter } from "next/font/google";
import Sidebar from '@/components/Sidebar.jsx';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="md:flex">
          <div className="sticky top-0 md:w-1/4">
          <Sidebar />
          </div>
          <div className="bg-white w-full md:w-3/4">{children}</div>
        </div>
      </body>
    </html>
  );
}